spring:
  profiles:
    active: db
  jackson:
    default-property-inclusion: non_null
  #    静态资源映射
  #  mvc:
#    static-path-pattern:/upload/**
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,\
#      classpath:/static/upload/,classpath:/public/,file:D://mall/upload/

mybatis:
  type-handlers-package: com.cskaoyan.typeHandler
pagehelper:
  helper-dialect: mysql
logging:
  level:
    com.cskaoyan.mapper: debug



