spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/19_cskaoyanmall_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

