spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/19_cskaoyanmall_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null

mybatis:
  type-handlers-package: com.cskaoyan.typeHandler
pagehelper:
  helper-dialect: mysql
logging:
  level:
    com.cskaoyan.mapper: debug



